### ISSUE TITLE
Accu level is not updated

### ISSUE THREAD

**Issue by oldman63** [koreader/KoboUSBMS#1]
Thank for this plugin, working fine on Kobo Aura H2O v1 device. The hungarian translating is worked. 👍 

Small problem: the accu level info is not updated while koboUSBMS module is active (attached to PC).

**Comment by NiLuJe** [comment]
I know: there's no actual event for this, so it happens only when *other* things happens ^^.

**Comment by NiLuJe** [comment]
Oh, wait, I just thought of something stupidly simple I could try to work it around...

I'll check later tonight ;).

**Comment by NiLuJe** [comment]
There, fixed in 0.9.4 ;).
